// <auto-generated />
using System;
using AnimalAtlas.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalAtlas.Infrastructure.Migrations
{
    [DbContext(typeof(AnimalAtlasContext))]
    [Migration("20241129104939_ParentNullable")]
    partial class ParentNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalAtlas.Infrastructure.Models.TaxonomyGroup", b =>
                {
                    b.Property<int>("TaxonomyGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaxonomyGroupId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxonomyGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaxonomyGroupId");

                    b.ToTable("TaxonomyGroups");
                });

            modelBuilder.Entity("AnimalAtlas.Infrastructure.Models.TaxonomyItem", b =>
                {
                    b.Property<int>("TaxonomyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaxonomyItemId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("TaxonomyItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaxonomyItemId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentId");

                    b.ToTable("TaxonomyItems");
                });

            modelBuilder.Entity("AnimalAtlas.Infrastructure.Models.TaxonomyItem", b =>
                {
                    b.HasOne("AnimalAtlas.Infrastructure.Models.TaxonomyGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalAtlas.Infrastructure.Models.TaxonomyItem", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Group");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
